(autoload 'php-mode "php-mode")
(add-hook 'php-mode-hook
          (lambda ()
            ;; (c-set-style "stroustrup")
            ;; (c-set-offset 'case-label 4)
            ;; (c-set-offset 'arglist-intro 4)
            ;; (c-set-offset 'arglist-cont-nonempty 4)
            ;; (c-set-offset 'arglist-close 0)
            ;; (setq php-mode-coding-style 'pear)
            ;; (setq php-mode-coding-style 'drupal)
            (setq php-mode-coding-style 'wordpress)
            (set (make-local-variable 'indent-tabs-mode) t)))
